use siap;
select count(*) as total, estudiantes.Semestre from biblioteca inner join estudiantes on estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" group by estudiantes.Semestre;
select count(*) as total, estudiantes.Facultad from biblioteca inner join estudiantes on estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" group by estudiantes.Semestre;
select count(*) as total, estudiantes.Carrera from biblioteca inner join estudiantes on estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" group by estudiantes.Semestre;
select count(*) from biblioteca inner join estudiantes on estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" order by biblioteca.Fecha_Ingreso;
select estudiantes.Facultad, estudiantes.Carrera, estudiantes.Semestre, estudiantes.Personal_Universidad_No_Documento, biblioteca.Fecha_Ingreso, biblioteca.Fecha_Salida from biblioteca inner join estudiantes on estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" order by biblioteca.Fecha_Ingreso;
select count(*) as total, estudiantes.Facultad, estudiantes.Carrera, estudiantes.Semestre, estudiantes.Personal_Universidad_No_Documento, biblioteca.Fecha_Ingreso, biblioteca.Fecha_Salida from biblioteca inner join estudiantes on estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where estudiantes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" group by estudiantes.Personal_Universidad_No_Documento;

select docentes.Facultad, docentes.Sede, docentes.Cargo, docentes.Personal_Universidad_No_Documento, biblioteca.Fecha_Ingreso, biblioteca.Fecha_Salida from biblioteca inner join docentes on docentes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where docentes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" order by biblioteca.Fecha_Ingreso;
select count(*) from biblioteca inner join docentes on docentes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where docentes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" order by biblioteca.Fecha_Ingreso;

select count(*) as total, docentes.Facultad from biblioteca inner join docentes on docentes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where docentes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" group by docentes.Facultad;
select count(*) as total, docentes.Sede from biblioteca inner join docentes on docentes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento where docentes.Personal_Universidad_No_Documento = biblioteca.Personal_Universidad_No_Documento and biblioteca.Fecha_Ingreso between "2022-09-01 00:00:00" and "2022-09-30 00:00:00" group by docentes.sede;
